Feature/sax
proteus-h2020/proteus-job pull request #15
Opened 2017-06-23 12:16 UTC by dhiguero

#### What's this PR do?

Adds the SAX operation to the Proteus Job.

#### Where should the reviewer start?

The `ProteusJob` now launches both the moments and the SAX operations. For SAX, two new variables have been added

```
--sax-model-storage-path   The path where the trained dictionary is stored
--sax-variable             The variable to be analyzed by SAX. Supports lists with comma.
```

The `SAXOperation` defines the SAX + SAXDictionary transformation of data. Notice that the output of `SAXDictionary` is joined with the X1 and X2 values that generated it. The code for doing that is based on the same approach as in `MomentsOperation` given the joining semantics. Two queues one for `SAXPrediction` and other for `(X1, X2)` tuples are maintained and joined whenever possible.

#### What is missing?

#### How should this be manually tested?

Unit tests are included
#### Any background context you want to provide?
#### Screenshots (if appropriate)
#### Questions:

2017-06-23 12:23 UTC, 0xNacho requested changes

2017-06-23 12:23 UTC, 0xNacho commented on src/main/scala/eu/proteus/job/operations/data/serializer/SAXResultKryoSerializer.scala
> +  override def write(kryo: Kryo, output: Output, r: SAXResult): Unit = {
Could we optimize data types in the serialization process?

I suggest the followings ones:
* **coilId**: integer
* **varId**: integer (1-56). Note that you should parse the original string value (CXXXX) to an integer.
* **x1**: double (you are currently using long, and some original x values are double).
* **x2**: double (same as above)
* **classId**: byte
* **similarity**: double

2017-06-23 12:41 UTC, 0xNacho commented
An issue that we are experiencing with the current implementation of SAX:
![image](https://user-images.githubusercontent.com/2890475/27482417-aaaa305e-5821-11e7-8c92-5502aa3e3dc2.png)

As you can see, we are getting two different **classId** values for the same [x1.x2] range.

2017-06-26 12:39 UTC, VenturaDelMonte requested changes
Very well-made PR! Let's try to address Nacho's request and then we merge it.

2017-06-26 12:39 UTC, VenturaDelMonte commented on src/main/scala/eu/proteus/job/kernel/ProteusJob.scala
> +      val variables = parameters.get("sax-variable").split(",")
let's use getRequired here instead of get. This will ensure a safe-failing in case the parameter is not set.

2017-06-26 12:39 UTC, VenturaDelMonte commented on src/main/scala/eu/proteus/job/kernel/ProteusJob.scala
> +          parameters.get("sax-model-storage-path"),
let's use getRequired here instead of get. This will ensure a safe-failing in case the parameter is not set.

2017-06-26 12:39 UTC, VenturaDelMonte commented on src/main/scala/eu/proteus/job/operations/data/serializer/SAXResultKryoSerializer.scala
> +  override def write(kryo: Kryo, output: Output, r: SAXResult): Unit = {
I agree with Nacho.

2017-06-26 14:07 UTC, dhiguero commented on src/main/scala/eu/proteus/job/operations/data/serializer/SAXResultKryoSerializer.scala
> +  override def write(kryo: Kryo, output: Output, r: SAXResult): Unit = {
I have modified X1 and X2 to be double. However I am not sure about changing variable name and classId. Class identifier is something that will be defined by the users and could just be a textual description of the category. What do you think?

2017-06-26 14:22 UTC, dhiguero commented
I cannot reproduce the duplicate output on the Kafka topic. I have checked and the serializer `write` method is called twice, but only one that call corresponds to the `FlinkKafkaProducer010.invokeInternal(T nex, long elementTimestamp)` method.

2017-06-27 07:31 UTC, VenturaDelMonte commented on src/main/scala/eu/proteus/job/operations/sax/SAXOperation.scala
> +      this.join(in1, coords, collector)
See above.

2017-06-27 07:31 UTC, VenturaDelMonte commented on src/main/scala/eu/proteus/job/operations/sax/SAXOperation.scala
> +      this.join(prediction, (in2._1, in2._2) , collector)
Due to how rocksdb works, after we perform a dequeue, we need to update the state for the given key. I will provide a better solution after RP1. This should fix the bug reported by @0xNacho.

2017-06-27 07:31 UTC, VenturaDelMonte commented on src/main/scala/eu/proteus/job/operations/data/serializer/SAXResultKryoSerializer.scala
> +  override def write(kryo: Kryo, output: Output, r: SAXResult): Unit = {
Then, both options are fine with me. Perhaps, @0xNacho might want to add more on this.

2017-06-27 10:58 UTC, 0xNacho approved these changes

2017-06-27 13:28 UTC, VenturaDelMonte commented
LGTM!

2017-06-27 13:36 UTC, VenturaDelMonte approved these changes

2017-06-27 13:36 UTC, VenturaDelMonte commented
Merged.

2017-06-27 13:36 UTC, closed without merging